word = input()
count = 0
count += word.count("dz=")
word = word.replace("dz=", " ")
count += word.count("c=")
word = word.replace("c=", " ")
count += word.count("c-")
word = word.replace("c-"," ")
count += word.count("d-")
word = word.replace("d-"," ")
count += word.count("lj")
word = word.replace("lj"," ")
count += word.count("nj")
word = word.replace("nj"," ")
count += word.count("s=")
word = word.replace("s="," ")
count += word.count("z=")
word = word.replace("z="," ")
print(count + len(word.replace(" ", "")))